name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/DatabaseVisualizer.sln
    - name: Build
      run: dotnet build ./src/DatabaseVisualizer.sln --no-restore
    - name: Test
      run: dotnet test ./src/DatabaseVisualizer.sln --no-build --verbosity normal
